const expenseList = [
  "food",
  "transportation",
  "utilities",
  "entertainment",
  "healthcare",
  "education",
  "personalCare",
  "clothing",
  "giftsAndDonations",
  "travel",
  "subscriptionsAndMemberships",
  "housing",
  "insurance",
  "savingsAndInvestments",
  "debtPayments",
  "childcare",
  "petCare",
  "homeMaintenance",
  "taxes",
  "emergencyFund",
  "luxuryItems",
  "professionalDevelopment",
  "hobbies",
  "technologyAndGadgets",
  "fitnessAndWellness",
  "socialActivities",
  "culturalExperiences",
  "legalExpenses",
  "others",
];

export default expenseList;
